# Generated by Django 2.0.2 on 2018-06-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('kategoria', models.CharField(max_length=100)),
                ('wersja', models.CharField(max_length=100)),
            ],
        ),
    ]
